Sprint 1/step 2
KateYachmeneva/ReactBurger pull request #1
Opened 2023-08-06 19:42 UTC by KateYachmeneva

2023-08-07 07:31 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Есть отписка от слушателя событий
- Есть проверка успешности запроса
- Запрос содержится в отдельном файле

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

**Необходимо исправить**

- Проект не собирается из-за отсутствующих импортов. Но если их поправить, то возникает ошибка с модальным окном. Всё дело в том, что div в который модальное окно должно портироваться отсутствует в файле index.html.

<img width="753" alt="Снимок экрана 2023-08-07 в 10 26 16" src="https://github.com/KateYachmeneva/ReactBurger/assets/60173362/cdcdbed6-d280-4186-92de-03dd62b45ddd">

<img width="851" alt="Снимок экрана 2023-08-07 в 10 27 30" src="https://github.com/KateYachmeneva/ReactBurger/assets/60173362/4f2c94fb-f71e-4c9e-926d-4680097af0cf">

- У всех компонентов с пропсами должны быть `propTypes`
- У `BurgerIngredient ` propTypes не соответствует пропсам
- Окно с деталями ингредиента должно показываться только при нажатии на ингредиент. 

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-08-07 07:31 UTC, andryxxa93 commented on src/components/Modal/Modal.jsx
> +        return () => document.removeEventListener ("keydown", closeWithEscape);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2023-08-09 11:52 UTC, andryxxa93 commented
**Необходимо исправить**
- Модальное окно должно закрываться нажатием на подложку - ModalOverlay. Сама подложка должна быть полупрозрачная.

2023-08-09 12:49 UTC, KateYachmeneva commented
Добрый день.
Замечание поправила

2023-08-09 12:58 UTC, KateYachmeneva commented
Добавила opacity

2023-08-09 14:07 UTC, KateYachmeneva commented
props поправила

2023-08-10 06:01 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-08-22 08:31 UTC, merged